### ISSUE TITLE
Error deserialising recurrence rule

### ISSUE THREAD

**Issue by stap123** [ical-org/ical.net#374]
I'm having an issue parsing a recurrence rule even though it's valid. I have used several online sources to ensure the rule is valid but am receiving an exception when trying to add it using the following:

`vEvent.RecurrenceRules.Add(new Ical.Net.DataTypes.RecurrencePattern(options.RecurrenceRule));`

The rule is this : "FREQ=DAILY;INTERVAL=1;COUNT=2" which I am pretty confident is valid. I receive the following exception:

```
System.Exception: FrequencyType.NONE cannot be evaluated. Please specify a FrequencyType before evaluating the recurrence.
   at Ical.Net.Evaluation.Evaluator.IncrementDate(DateTime& dt, RecurrencePattern pattern, Int32 interval) in C:\git\ical.net\net-core\Ical.Net\Evaluation\Evaluator.cs:line 85
   at Ical.Net.Evaluation.RecurrencePatternEvaluator.GetDates(IDateTime seed, DateTime periodStart, DateTime periodEnd, Int32 maxCount, RecurrencePattern pattern, Boolean includeReferenceDateInResults)
   at Ical.Net.Evaluation.RecurrencePatternEvaluator.Evaluate(IDateTime referenceDate, DateTime periodStart, DateTime periodEnd, Boolean includeReferenceDateInResults) in C:\git\ical.net\net-core\Ical.Net\Evaluation\RecurrencePatternEvaluator.cs:line 894
   at Ical.Net.Evaluation.RecurringEvaluator.<>c__DisplayClass7_0.<EvaluateExRule>b__0(RecurrencePattern exRule) in C:\git\ical.net\net-core\Ical.Net\Evaluation\RecurringEvaluator.cs:line 90
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Ical.Net.Evaluation.RecurringEvaluator.EvaluateExRule(IDateTime referenceDate, DateTime periodStart, DateTime periodEnd) in C:\git\ical.net\net-core\Ical.Net\Evaluation\RecurringEvaluator.cs:line 92
   at Ical.Net.Evaluation.RecurringEvaluator.Evaluate(IDateTime referenceDate, DateTime periodStart, DateTime periodEnd, Boolean includeReferenceDateInResults) in C:\git\ical.net\net-core\Ical.Net\Evaluation\RecurringEvaluator.cs:line 124
   at Ical.Net.Evaluation.EventEvaluator.Evaluate(IDateTime referenceTime, DateTime periodStart, DateTime periodEnd, Boolean includeReferenceDateInResults) in C:\git\ical.net\net-core\Ical.Net\Evaluation\EventEvaluator.cs:line 41
   at Ical.Net.Evaluation.RecurrenceUtil.GetOccurrences(IRecurrable recurrable, IDateTime periodStart, IDateTime periodEnd, Boolean includeReferenceDateInResults) in C:\git\ical.net\net-core\Ical.Net\Evaluation\RecurrenceUtil.cs:line 36
   at Ical.Net.Calendar.<>c__DisplayClass60_0`1.<GetOccurrences>b__0(T recurrable) in C:\git\ical.net\net-core\Ical.Net\Calendar.cs:line 287
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Ical.Net.Calendar.GetOccurrences[T](IDateTime startTime, IDateTime endTime) in C:\git\ical.net\net-core\Ical.Net\Calendar.cs:line 289
   at Ical.Net.Calendar.GetOccurrences(DateTime startTime, DateTime endTime) in C:\git\ical.net\net-core\Ical.Net\Calendar.cs:line 256
```

Is it something wrong with what I am doing or a bug in the library?

Any Help Appreciated.

**Comment by rianjs** [comment]
Can you post the full ICS text that fails? (Or a small subset that will triggers the problem you describe if I were to put it into a unit test.)

**Comment by stap123** [comment]
It's not actually coming from an ICS feed, I am just trying to use this part of the library to generate the occurrences. 

I'm trying to populate minimum data possible to get the occurrences so presently I just do this:

 ```
var vEvent = new Ical.Net.CalendarComponents.CalendarEvent
{
    DtEnd = new Ical.Net.DataTypes.CalDateTime(options.EndTime),
    DtStart = new Ical.Net.DataTypes.CalDateTime(options.StartTime),                
};
vEvent.ExceptionRules.Add(new Ical.Net.DataTypes.RecurrencePattern(options.RecurrenceException));
vEvent.RecurrenceRules.Add(new Ical.Net.DataTypes.RecurrencePattern(options.RecurrenceRule));

var vCalendar = new Ical.Net.Calendar();
vCalendar.Events.Add(vEvent);

var occurances = vCalendar.GetOccurrences(DateTime.Now, academicYear.EndDate);
```

The content in options.RecurrenceRule is "FREQ=DAILY;INTERVAL=1;COUNT=2"

It errors on the line starting vEvent.RecurrenceRules.Add...

**Comment by stap123** [comment]
In case it's useful when splitting the line up into this, the error happens on the RecurrenceRules.Add line:

```
var pat = new Ical.Net.DataTypes.RecurrencePattern(options.RecurrenceRule);
vEvent.RecurrenceRules.Add(pat);
```

**Comment by rianjs** [comment]
I just tried to replicate your problem using nuget package 4.latest:

```csharp
var rPattern = new RecurrencePattern("FREQ=DAILY;INTERVAL=1;COUNT=2");
var specifiedRecurrencePattern = new RecurrencePattern(FrequencyType.Daily, 1)
{
    Count = 2,
};
var same = rPattern.Equals(specifiedRecurrencePattern); //true
```

**Comment by stap123** [comment]
@rianjs The rule parsing actually seems to be working fine, it was the `vEvent.RecurrenceRules.Add(rPattern);` that was failing.

So I have got what I wanted working but not by using it in the same way. I found a blog post here http://www.programering.com/a/MjM4cTMwATc.html which shows using a class called `RecurringComponent` so I stopped using the `CalendarEvent` object and started using that instead that now seems to allow me to generate the events that would occur. My final working code is below in case it's useful to someone else. 

```
var recComp = new Ical.Net.CalendarComponents.RecurringComponent();
var pat = new Ical.Net.DataTypes.RecurrencePattern(options.RecurrenceRule);
recComp.RecurrenceRules.Add(pat);
recComp.Start = new Ical.Net.DataTypes.CalDateTime(options.StartTime);
var occurences = recComp.GetOccurrences(DateTime.Now, DateTime.Now.AddMonths(6));
```

Apologies if the start of this issue was misleading. Maybe the result could be a a more meaningful error message when that add method is called without the correct properties being set. (Or maybe I was just trying to use the wrong thing for the job I wanted)

Thanks for the quick response though, very much appreciated and great library for simplifying something so complex.

**Comment by rianjs** [comment]
> The rule parsing actually seems to be working fine, it was the vEvent.RecurrenceRules.Add(rPattern); that was failing.

That's weird. o_O Both of these ways of adding work for me:

```csharp
var rPattern = new RecurrencePattern("FREQ=DAILY;INTERVAL=1;COUNT=2");
var e = new CalendarEvent
{
    Start = new CalDateTime(DateTime.Now),
    End = new CalDateTime(DateTime.Now.AddHours(1)),
    RecurrenceRules = new List<RecurrencePattern> { rPattern },
};
e.RecurrenceRules.Add(rPattern);
```
