### ISSUE TITLE
Offset must be specified in whole minutes - for certain timezones on Calendar.AddTimezone

### ISSUE THREAD

**Issue by davidMuir** [ical-org/ical.net#376]
Getting an `ArgumentException` of `Offset must be specified in whole minutes` when calling `Calendar.AddTimezone` for three windows timezones:

- SA Western Standard Time (-4h 0m)
- Arab Standard Time (3h 0m)
- Afghanistan Standard Time 

Exception:

```
Unhandled Exception: System.ArgumentException: Offset must be specified in whole minutes.
Parameter name: offset
   at System.DateTimeOffset.ValidateOffset(TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
   at Ical.Net.CalendarComponents.VTimeZone.FromDateTimeZone(String tzId, DateTime earlistDateTimeToSupport, Boolean includeHistoricalData) in C:\git\ical.net\net-core\Ical.Net\CalendarComponents\VTimeZone.cs:line 57
   at Ical.Net.CalendarComponents.VTimeZone.FromSystemTimeZone(TimeZoneInfo tzinfo) in C:\git\ical.net\net-core\Ical.Net\CalendarComponents\VTimeZone.cs:line 23
   at Ical.Net.Calendar.AddTimeZone(TimeZoneInfo tzi) in C:\git\ical.net\net-core\Ical.Net\Calendar.cs:line 393
   at ICal_Net_Timezone_Bug_Repro.Program.Run() in C:\Users\David\Source\Repos\misc\ICal_Net_Timezone_Bug_Repro\Program.cs:line 39
   at ICal_Net_Timezone_Bug_Repro.Program.Main(String[] args) in C:\Users\David\Source\Repos\misc\ICal_Net_Timezone_Bug_Repro\Program.cs:line 12
```

Console App to find failing timezones:

```c#
using System;
using System.Collections.Generic;
using Ical.Net;
using Ical.Net.CalendarComponents;

namespace ICal_Net_Timezone_Bug_Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            new Program().Run();
        }

        void Run()
        {
            var cal = new Calendar();

            var timezones = TimeZoneInfo.GetSystemTimeZones();

            foreach(var timezone in timezones)
            {
                try
                {
                    cal.AddTimeZone(timezone);
                }
                catch (Exception e)
                {
                    // Ignore timezones that couldn't be found
                    if (!e.Message.Contains("Offset")) continue;

                    var offset = $"{timezone.BaseUtcOffset.Hours}h {timezone.BaseUtcOffset.Minutes}m";

                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"{timezone.Id} ({offset}) --- {e.Message}");
                    Console.ResetColor();

                    continue;
                }
            }
        }
    }
}
```

Result from above program:

```
SA Western Standard Time (-4h 0m) --- Offset must be specified in whole minutes.
Parameter name: offset
Arab Standard Time (3h 0m) --- Offset must be specified in whole minutes.
Parameter name: offset
Afghanistan Standard Time (4h 30m) --- Offset must be specified in whole minutes.
Parameter name: offset
```

**Comment by forger** [comment]
I can reproduce the exception with the following example run on either NodaTime NuGet Version 1.4.3 and 1.4.5.
I haven't tried v2 because I'm stuck with target framework .NET 4 for the host project & the time being.

```csharp
public DateTimeOffset ReproduceArgumentException()
{

    var zone = DateTimeZoneProviders.Tzdb["Asia/Shanghai"];
    var dateTime = new DateTime(1900, 6, 30, 0, 2, 0, DateTimeKind.Unspecified);
    
    //notice: zonedDateTime.Offset contains seconds: +08:05:43
    //also: InZoneStrictly() yields the same result as far as I can tell
    var zonedDateTime = LocalDateTime.FromDateTime(dateTime).InZoneLeniently(zone);

    return zonedDateTime.ToDateTimeOffset(); //throws the following
    /* System.ArgumentException: Offset must be specified in whole minutes.
        Parameter name: offset
            at System.DateTimeOffset.ValidateOffset(TimeSpan offset)
            at System.DateTimeOffset..ctor(Int64 ticks, TimeSpan offset)
            at NodaTime.ZonedDateTime.ToDateTimeOffset() */
}
```

Any suggestions on how to handle this?
