### ISSUE TITLE
Calendar.LoadFromStream is not thread safe

### ISSUE THREAD

**Issue by rianjs** [ical-org/ical.net#40]
```
System.ArgumentException occurred
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Ical.Net.Utility.SerializationUtil.GetDeserializingMethods(Type targetType) in C:\dev\ical.net\ical.NET\Utility\SerializationUtil.cs:line 60
  InnerException:
```

Repro case. Code works fine if `.AsParallel()` is removed.

``` csharp
public static IEnumerable<DowntimeWithExactTimes> GetDowntimesInRange(IEnumerable<Downtime> downtimes, DateTime earliestStart, DateTime latestEnd)
{
    var sw = new Stopwatch();
    sw.Start();
    var earliestStartIcal = new CalDateTime(earliestStart, "UTC") {HasTime = true};
    var latestEndIcal = new CalDateTime(latestEnd, "UTC") {HasTime = true};
    var downtimesWithExactTimes = downtimes.AsParallel().SelectMany(downtime =>
    {
        IICalendarCollection calendar;
        using (var reader = new StringReader(downtime.IcalString ?? ""))
        {
            // Originally calendar = iCalendar.LoadFromStream(reader), but that uses a static serializer so it isn't thread safe.
            //calendar = Calendar.LoadFromStream(reader);
            calendar = Calendar.LoadFromStream(reader, new CalendarSerializer { SerializationContext = new SerializationContext() });
        }

        var thisDowntime = downtime;
        var occurrences = calendar.GetOccurrences(earliestStartIcal, latestEndIcal);
        return occurrences.Select(occurrence => new DowntimeWithExactTimes(thisDowntime, occurrence.Period.StartTime.AsUtc, occurrence.Period.EndTime.AsUtc));
    });
    var orderedDowntimes = downtimesWithExactTimes.OrderBy(downtime => downtime.Start).ThenBy(downtime => downtime.End).ToList();
    sw.Stop();
    return orderedDowntimes;
}
```

**Comment by rianjs** [comment]
This is related to the caching I introduced last weekend. Crap.

**Comment by rianjs** [comment]
188889e53028f76a5a2700790641192f5d60e0fe
