### ISSUE TITLE
Version Mismatch with NodaTime

### ISSUE THREAD

**Issue by SirSparkles** [ical-org/ical.net#440]
Hi, 

Similar to #301 

There seems to be a version mismatch in the latest bundled version. Version 2.0.2.0 is specifically linked.

Cheers

2019-02-23 10:57:18|INFO| Output File to: C:\Users\Mark\Documents\TVR Sample Docs\test.xml 
2019-02-23 10:57:18|ERROR| System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1'
   at Ical.Net.DataTypes.CalDateTime.get_AsUtc()
   at Ical.Net.DataTypes.CalDateTime.op_Subtraction(CalDateTime left, IDateTime right)
   at Ical.Net.CalendarComponents.CalendarEvent.ExtrapolateTimes()
   at Ical.Net.CalendarComponents.CalendarEvent.set_DtEnd(IDateTime value)
   at TVRename.UpcomingiCAL.Generate(Stream str, List`1 elist)

=== Pre-bind state information ===
LOG: DisplayName = NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/TVRename/
LOG: Initial PrivatePath = NULL

Calling assembly : Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=65c0446cd019ea53.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1
LOG: Attempting download of new URL file:///C:/Program Files (x86)/TVRename/NodaTime.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
 System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1'
   at Ical.Net.DataTypes.CalDateTime.get_AsUtc()
   at Ical.Net.DataTypes.CalDateTime.op_Subtraction(CalDateTime left, IDateTime right)
   at Ical.Net.CalendarComponents.CalendarEvent.ExtrapolateTimes()
   at Ical.Net.CalendarComponents.CalendarEvent.set_DtEnd(IDateTime value)
   at TVRename.UpcomingiCAL.Generate(Stream str, List`1 elist)

**Comment by tonihele** [comment]
I don't know whether this is a bug or not. Probably not. If you are using NodaTime in your project elsewhere, just put the assembly binding for the correct version to you project configuration to fix this problem.

We are happily using NodaTime 2.4.6 and everything seems to work...

**Comment by baptistecdr** [comment]
@tonihele Thanks you ! Indeed it works fine when you add NodaTime (from NuGet) and then iCal.NET 👍
