### ISSUE TITLE
System.NotSupportedException when using .Net Core 3.1

### ISSUE THREAD

**Issue by mtemmen-ww** [ical-org/ical.net#481]
I've just upgraded my project from .Net Core 2.2 to 3.1, but now I'm getting this error:
`"System.NotSupportedException: The collection type 'Ical.Net.IParameterCollection' on 'Ical.Net.DataTypes.RecurrencePattern.Parameters' is not supported."`
I tried it with both version 4.1.8 and 3.0.15 (as mentioned in #475 ) with the same result. Here's the last part of the stack trace:
```System.NotSupportedException: The collection type 'Ical.Net.IParameterCollection' on 'Ical.Net.DataTypes.RecurrencePattern.Parameters' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonPropertyInfo.get_RuntimeClassInfo()
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
```

**Comment by pantonis** [comment]
@mtemmen-ww Did you manage to make it work with .NET Core 3.1?

**Comment by mtemmen-ww** [comment]
Yes, I think it was related to the new JSON serializer in .NET Core  3. Since my project is using the API template, I changed my ConfigureServices() in the Startup.cs to:
```
public void ConfigureServices(IServiceCollection services)
{
        services.AddControllers().AddNewtonsoftJson();
}
```
to use Newtonsoft.JSON again and that fixed it.
